token: ur token here plz
cloud_translation_api_key: # grab api key from https://console.cloud.google.com/apis/api/translate.googleapis.com/credentials
private_key_file: # path to your private key file (service account), make sure to escape string if you're using windows!
project_id: # your project id on google cloud